# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  PY: e
  ANGR_REPO: angr

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.6'
    architecture: 'x64'

- script: |
    echo Installing dependencies
    ( curl https://raw.githubusercontent.com/angr/angr-dev/wip/azure/tests/azure-install.sh | grep -v 404 || curl https://raw.githubusercontent.com/angr/angr-dev/wip/azure/tests/azure-install.sh ) | bash
  displayName: 'Installing dependencies'

- script: |
    echo Run tests
    ~/angr-dev/tests/azure-test.sh
  displayName: 'Run tests'
